### ISSUE TITLE
Switch to an open source license

### ISSUE THREAD

**Issue by dhimmel** [fanglab/mbin#3]
The [current license](https://github.com/fanglab/mbin/blob/2830fec63485477d1791abf29518a2761d241579/LICENSE) is CC BY-NC-SA 4.0, which is not an open source software license.

From the [Creative Commons FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software):

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.
>
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

The [paper](https://doi.org/10.1038/nbt.4037) mentions funding from [`R01-GM114472-01`](http://grantome.com/grant/NIH/R01-GM114472-01), so I'm assuming this work is intended to be reusable by the public!

A list of recommended open source software licenses is [available from the OSI](https://opensource.org/licenses). Happy to answer any questions to the best of my abilities on the implications of different licenses.

**Comment by dhimmel** [comment]
Note that the [PyPI release](https://pypi.python.org/pypi/mbin/1.0.4) claims the license is BSD:

https://github.com/fanglab/mbin/blob/2830fec63485477d1791abf29518a2761d241579/setup.py#L45

The [BSD 3-Clause license](https://opensource.org/licenses/BSD-3-Clause) is great for software and is commonly used by Python packages. Just it's important that the repositories LICENSE file matches the license specified in the metadata.

**Comment by jbeaulaurier** [comment]
Hi Daniel,

This license was advised by our school considering multiple factors. We certainly do want to encourage broad academic use of the code for research, but the IP is covered by a provisional patent and therefore we would like to limit unauthorized commercial use (for which it will be determined case by case by contacting the Mount Sinai Innovation Partners group at MSIPInfo@mssm.edu). Also, as mentioned in the paper, this paper was funded partially by the NIH grant and other resources.

Also, thanks for pointing out the license typo in the setup.py file. This was fixed in 506e66a.

Best,
John
